# Generated by Django 5.0.1 on 2024-09-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternative_mobile_number', models.CharField(blank=True, max_length=15)),
                ('convenient_time_to_call', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('show_permanent_address', models.BooleanField(default=False)),
                ('show_working_address', models.BooleanField(default=False)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='app.basicinformation')),
            ],
        ),
    ]
