# Generated by Django 5.0.1 on 2024-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactus_show_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='show_permanent_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='show_working_address',
            field=models.TextField(),
        ),
    ]
