# Generated by Django 5.0.1 on 2024-09-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetailes',
            name='family_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='family_values',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='familystaychoice',
            field=models.CharField(choices=[('My parents will stay with me after marriage', 'My parents will stay with me after marriage'), ('My parents will not stay with me after marriage', 'My parents will not stay with me after marriage'), ('Dont wish to specify', 'Dont wish to specify')], max_length=60),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='fathername',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='fatheroccupation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='mothername',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='motheroccupation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='familydetailes',
            name='mothertounge',
            field=models.CharField(max_length=70),
        ),
    ]
