# Generated by Django 5.0.1 on 2024-09-17 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_often_do_you_go_out', models.CharField(choices=[('Rarely', 'Rarely'), ('Occasionally', 'Occasionally'), ('Frequently', 'Frequently'), ('Always', 'Always')], max_length=20)),
                ('how_would_you_describe_your_clothes', models.TextField()),
                ('how_do_you_spend_your_free_time', models.TextField()),
                ('how_many_times_do_you_visit_salon_or_beauty_parlour', models.PositiveIntegerField()),
                ('how_many_times_do_you_go_out_drinking_or_in_a_pub', models.PositiveIntegerField()),
                ('what_would_you_choose_for_a_romantic_date_with_your_partner', models.TextField()),
                ('which_social_platform_do_you_use_most', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], max_length=20)),
                ('do_you_like_shopping', models.BooleanField()),
                ('preferences_while_traveling', models.TextField()),
                ('which_personality_are_you', models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert'), ('Ambivert', 'Ambivert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ImageField(blank=True, null=True, upload_to='address_id/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habits', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IdProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='id_proofs/')),
                ('passport_size_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreferenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('height_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('complexion', models.CharField(choices=[('Fair', 'Fair'), ('Wheatish', 'Wheatish'), ('Dark', 'Dark'), ('Any', 'Any')], max_length=10)),
                ('residency_status', models.CharField(choices=[('Citizen', 'Citizen'), ('Permanent Resident', 'Permanent Resident'), ('Temporary Resident', 'Temporary Resident')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('partner_expectations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCompletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.BooleanField()),
                ('basic_details_completed', models.BooleanField()),
                ('education_details_completed', models.BooleanField()),
                ('horoscope_details_completed', models.BooleanField()),
                ('family_details_completed', models.BooleanField()),
                ('partner_preference_details_completed', models.BooleanField()),
                ('habits_details_completed', models.BooleanField()),
                ('hobbies_details_completed', models.BooleanField()),
                ('interest_details_completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SixPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='six_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField()),
                ('descriptions', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
